# Encoders
encoder:
    d_input: 3           # Number of input dimensions
    n_freqs: 10          # Number of encoding functions for samples
    log_space: True      # If set, frequencies scale in log space
    use_viewdirs: True   # If set, use view direction as input
    n_freqs_views: 4     # Number of encoding functions for views

# Stratified sampling
stratified_sampling:
    n_samples: 64         # Number of spatial samples per ray
    perturb: True         # If set, applies noise to sample positions
    inverse_depth: False  # If set, samples points linearly in inverse depth

# Model
model: 
    d_input: 3
    d_filter: 128          # Dimensions of linear layer filters
    n_layers: 2            # Number of layers in network bottleneck
    skip: []               # Layers at which to apply input residual
    # d_viewdirs: None
    use_fine_model: True   # If set, creates a fine model
    d_filter_fine: 128     # Dimensions of linear layer filters of fine network
    n_layers_fine: 6       # Number of layers in fine network bottleneck
    near: 2.0
    far: 6.0

# Hierarchical sampling
hierarchical_sampling:
    n_samples_hierarchical: 64   # Number of samples per ray
    perturb_hierarchical: False  # If set, applies noise to sample positions

# Optimizer
optimizer:
    lr: 0.0005  # Learning rate

# Training
train:
    n_iters: 10000
    batch_size: 16384          # Number of rays per gradient step (power of 2) -> 2**14 = 16384
    one_image_per_step: True   # One image per gradient step (disables batching)
    chunksize: 16384           # Modify as needed to fit in GPU memory -> 2**14 = 16384
    center_crop: True          # Crop the center of image (one_image_per_)
    center_crop_iters: 50      # Stop cropping center after this many epochs
    display_rate: 25          # Display test output every X epochs

# Early Stopping
early_stop:
    warmup_iters: 100          # Number of iterations during warmup phase
    warmup_min_fitness: 10.0   # Min val PSNR to continue training at warmup_iters
    n_restarts: 10             # Number of times to restart if training stalls